# _config.yml
title: Maximum Entertainment Developer API
description: Comprehensive API documentation for our services.
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
plugins:
  - jekyll-feed

sidebar:
  enabled: false


