# _config.yml
title: "Maximum Entertainment Developer API"
description: "Comprehensive API documentation for our services."
remote_theme: pmarsceill/just-the-docs
markdown: kramdown

# Sidebar navigation
just_the_docs:
  show_toc: true  # Show the table of contents on each page
  toc_levels: "1..3"  # Include headings (H1, H2, H3)
  search_enabled: true  # Enable search functionality
  search_tokenizer_separator: /[\s]+/  # Tokenizer for search

# Markdown and highlighter settings
markdown: kramdown
highlighter: rouge

# Plugins for Just the Docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Configuration to use README.md as the index page
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: "/"
