# _config.yml
title: Maximum Entertainment Developer API
description: Comprehensive API documentation for our services.
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
plugins:
  - jekyll-feed

minimal_mistakes_skin: default
sidebar:
  enabled: false

# Basic configuration options for Tactile:
permalink: pretty
# Theme configuration options
minimal_mistakes_skin: "default" # Choose a skin (theme variation) if needed

