# _config.yml
title: Maximum Entertainment Developer API
description: Comprehensive API documentation for our services.
remote_theme: just-the-docs/just-the-docs  # Use just-the-docs as a remote theme
markdown: kramdown
plugins:
  - jekyll-feed

# Configure Just the Docs navigation
just_the_docs:
  show_sidebar: true
  search_enabled: true

  collections:
    - label: "API Reference"
      items:
        - label: "Generate Access Token"
          path: "#generate-access-token"
        - label: "Access Physical Sales Data"
          path: "#access-physical-sales-data"
        - label: "Access Digital Sales Data"
          path: "#access-digital-sales-data"
