# _config.yml
title: Maximum Entertainment Developer API
description: Comprehensive API documentation for our services.
remote_theme: pages-themes/tactile@v0.2.0
markdown: kramdown
plugins:
  - jekyll-feed

# Optional: Tactile theme settings
# Tactile is a clean theme, so it does not have a sidebar by default.
# You can adjust the colors and basic styling using custom CSS if needed.

# Basic configuration options for Tactile:
permalink: pretty
theme: tactile

