# _config.yml
title: Maximum Entertainment Developer API
description: Comprehensive API documentation for our services.
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
plugins:
  - jekyll-feed

# Configure Just the Docs settings
just_the_docs:
  show_sidebar: false
  search_enabled: false
  show_toc: true        # Ensures the table of contents shows up

# Add this to your _config.yml
defaults:
  - scope:
      path: ""
      type: "css"
    values:
      assets:
        css:
          - /assets/css/custom.css
